### ISSUE TITLE
macOS install - convertAI2RPR script missing

### ISSUE THREAD

**Issue by verstaerkermusic** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#141]
the mentioned script (and all other convertScritps )are missing ... 

When you call the the convert Arnold Scene from the menu you'll get an error:

```
# Error: cannot import name convertAI2RPR
# Traceback (most recent call last):
#   File "/Users/Shared/RadeonProRender/Maya/plugin/scripts/fireRender/fireRenderMenu.py", line 87, in convertArnoldToRPR
#     from . import convertAI2RPR as aiconvert
# ImportError: cannot import name convertAI2RPR # 
```

**Comment by DavidSpeicher** [comment]
Hi,

Thank you for reporting this issue, i have passed it to the developers.

**Comment by DavidSpeicher** [comment]
issue should be fixed on next release.

**Comment by verstaerkermusic** [comment]
Hi

just want to give feedback that this function is back working
