### ISSUE TITLE
Issue setting density in attribute editor for vdb file.

### ISSUE THREAD

**Issue by GravesCloud** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#163]
Hi,  I'm new to the world of 3D and I am having trouble.  My goal is to render smoke in prorender under maya 2020 on OSX using a radeon 470

Because I was having trouble in my scene I found https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/maya/openvdb_volumes.html

When I set project and open the .ma scenes I see the node indicator (box with dot in center) in the viewport but nothing renders.

When I open one of the example .ma files density appears in the section under density but if I were to save and reopen the file the value would say "not used".  I do have the checkmark clicked enabled.  It says density is on in the channel box editor.

I'm really hitting a brickwall I did see "AMD Radeon ProRender supports floating-point grids only. Other grid types are not supported at the moment."  on the page I linked earlier.  I understand changing maya unit size but perhaps my ignorance of floating point grids is the issue?

Edit:

I'm getting this error in the console:

`// Error: line 1: Cannot find procedure "fireRender". //`

I thought I was unable to read the VDB files.  
How do I go about fixing this?  I also am missing the rpr conversion scripts.

**Comment by GravesCloud** [comment]
It looks to me like this issue is already being addressed in the development branch.

I'm wondering if I should try reinstalling the package from the shell and set python version to 3.x ?
Is this my best course of action?

**Comment by DMotorygin** [comment]
> It looks to me like this issue is already being addressed in the development branch.
> 
> I'm wondering if I should try reinstalling the package from the shell and set python version to 3.x ?
> Is this my best course of action?

Do you have RPR1 or RPR2 selected? (Quality Tab : Engine >> Render Engine)
Select RPR1 should be selected because RPR2 doesn't support vdb volumes yet.

**Comment by GravesCloud** [comment]
<img width="598" alt="Screen Shot 2021-02-18 at 4 36 05 PM" src="https://user-images.githubusercontent.com/77372610/108440209-85cbde00-7207-11eb-9b55-42431260d15e.png">

Thank you for your reply, I was using rpr2!

However, I get this error now so I'm throwing in the towel.

**Comment by GravesCloud** [comment]
> Do you have RPR1 or RPR2 selected? (Quality Tab : Engine >> Render Engine)
> Select RPR1 should be selected because RPR2 doesn't support vdb volumes yet.

After reviewing the prorender promotion videos, the download page and the docs links regarding the plugin I don't see how I was to know this.
A big red banner across the top of the page that says:
"Don't waste your time with prorender, you need a cuda card and linux for any modern GPU accelerated rendering"
seems like the decent thing to do.
Now I'm glad there is a video card shortage or I'd be sitting on a useless (to me) 5700xt,  lucky me i guess.

**Comment by bsavery** [comment]
> "Don't waste your time with prorender, you need a cuda card and linux for any modern GPU accelerated rendering"

Sorry do you actually want help with your issue or just to complain? If you take a look at the "Known Issues" 
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin/blob/master/CHANGELOG.md#known-issues

It mentions using Legacy Mode (RPR 1) for volumes.  

I'm sorry you feel like ProRender is a waste of time but if you do have a problem with it you get access to developers directly to help you like right now.

**Comment by GravesCloud** [comment]
Thanks bsavery,

Thank you for pointing that out, I'm glad to hear you let people know ahead of time.

thank you.
