### ISSUE TITLE
IPR render is much faster then production render

### ISSUE THREAD

**Issue by dag08** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#222]
The production render needs to render over 9min on the same frame with the same settings for both renderer. The IPR render took 3:35 for this frame. This test was made over 5 times with the same result. System MacOS BigSur, Maya 2022/2020. I9-9900K,  64 GB, Radeon RX Vega64.
![Bildschirmfoto 2021-07-13 um 20 24 35](https://user-images.githubusercontent.com/17858969/125505705-481eeb5d-9620-43ef-abdc-be635f0d4415.png)
![Bildschirmfoto 2021-07-13 um 20 24 44](https://user-images.githubusercontent.com/17858969/125505714-aa2ee5b1-b102-4718-bbc3-c6efdb30e06a.png)
![Bildschirmfoto 2021-07-13 um 20 24 50](https://user-images.githubusercontent.com/17858969/125505721-653c07bf-0f1a-4bf3-af4a-a1acbf7309bf.png)

**Comment by DavidSpeicher** [comment]
Hi,

Is it possible you can provide scene ?

**Comment by DavidSpeicher** [comment]
Hi, 
Is it possible you can share a scene for this ? im getting slightly different results on our Mac system. 

I Passed this on to the developers to investigate. 

In IPR mode  we use preview mode for IPR which reduces quality and gives better speed. 
To increase your speed of Production slightly you could try adjusting the updates per samples, using 32 should help.

 Also we have different settings for quality settings check if they are the same.
