### ISSUE TITLE
Maya Radeon prorender not working

### ISSUE THREAD

**Issue by Quitoberry** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#251]
Hi, I can't seem to figure out why Maya always shows;
 Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:   Cannot find the specified program?

**Comment by DavidSpeicher** [comment]
Hi, 

unfortunately we do not support Maya 2018. we currently only support the last 3 version of Maya ( 2019 , 2020, and 2022) 
Sorry for the inconvenience
