### ISSUE TITLE
Problems with Radeon ProRender in viewport (crashes) and fail to use selected render cam

### ISSUE THREAD

**Issue by clasicodeguitarra** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#283]
Hi, I was adviced to generate a ticket here, I will try to provide information

Windows 10 build 1809
GPU AMD Radeon 480
Intel i-5
RAM 64 GB
Maya 2022
AMD drivers up to date

Well, in first Maya instalation I had issues with using RPR in the viewport panel. It usually rendered the current frame, but it crashed later.

In a second clean installation I was able to actually move around in the viewport while it rendered, but it crashed after a while. And nowaday it crashes right from the start. (critical error, unknown error).

I was able to get around just using the "render frame".

But another thing is that when I created a new camera and asigned as render cam, it doesnt work, and I started noticing an error report any time I create a new camera.

# Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/createMayaSoftwareCommonGlobalsTab.mel line 2077: AssertionError: file C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\maya\app\general\updateRenderableCamerasList.py line 58:  #

This messages appears any time I create a new camera. And "render current frame" only renders current camera, not the selected camera in the radeon render setup.

Well, hope there is some kind of solution! thanks

**Comment by DavidSpeicher** [comment]
Hi, 

Please provide scene. its possible it could be something in Render settings that is causing this crash.

**Comment by DavidSpeicher** [comment]
please check with latest release build 3.4
