### ISSUE TITLE
System Crash with RPR for Maya Plugin 2.9

### ISSUE THREAD

**Issue by GregBollella** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#3]
If I start a production render and have a window open with an online game I can reliably get the system to crash. System freezes. No inputs from mouse or keyboard. Eventually, system reboots. 

I will say I am very new to this modeling world... just having seriously started a few months ago. 

Maya 2020.1 (the latest version afaik)

online game, Second Life with Firestorm Viewer

scene
[SingleObjectTeakBenchSwingHighPolySceneWithRPRSurfacesNewSlab.mb.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin/files/4625178/SingleObjectTeakBenchSwingHighPolySceneWithRPRSurfacesNewSlab.mb.zip)

screenshots of system stats
![Screen Shot 2020-05-13 at 16 15 27](https://user-images.githubusercontent.com/7319340/81875808-fede2c80-9535-11ea-957c-7bbf42805053.png)
![Screen Shot 2020-05-13 at 16 16 34](https://user-images.githubusercontent.com/7319340/81875810-ff76c300-9535-11ea-9d09-2dc961f1ec34.png)

**Comment by GregBollella** [comment]
Forgot, I have an eGPU... Black Magic Pro that has a AMD Radeon RX Vega 56 and and driving an LG HDR 5K display through the eGPU

**Comment by bsavery** [comment]
Hey Greg.  Just to be clear, which device(s) do you have enabled when rendering to cause this?

**Comment by GregBollella** [comment]
I have the two GPUs enabled. The Pro Vega 20 and the RX Vega 56. Below are screenshots of my render settings. 

![Screen Shot 2020-05-13 at 17 03 30](https://user-images.githubusercontent.com/7319340/81878093-d2c5aa00-953b-11ea-81ef-028111b94104.png)

![Screen Shot 2020-05-13 at 17 03 39](https://user-images.githubusercontent.com/7319340/81878095-d3f6d700-953b-11ea-8510-343263adee52.png)

![Screen Shot 2020-05-13 at 17 02 09](https://user-images.githubusercontent.com/7319340/81878085-d0fbe680-953b-11ea-936b-a5b72b630006.png)
![Screen Shot 2020-05-13 at 17 02 34](https://user-images.githubusercontent.com/7319340/81878086-d1947d00-953b-11ea-8251-49215a013ab2.png)
![Screen Shot 2020-05-13 at 17 02 44](https://user-images.githubusercontent.com/7319340/81878087-d1947d00-953b-11ea-994e-0a11255e46cc.png)
![Screen Shot 2020-05-13 at 17 02 52](https://user-images.githubusercontent.com/7319340/81878088-d1947d00-953b-11ea-8e66-b367ba2516b8.png)
![Screen Shot 2020-05-13 at 17 02 59](https://user-images.githubusercontent.com/7319340/81878092-d2c5aa00-953b-11ea-9f63-f0a9d8f6092b.png)

**Comment by bsavery** [comment]
Ok, sorry for all the questions but this helps us narrow it down!  

Are you doing final renders or viewport?  
Secondly.  Does this happen with only one of the gpus or both?  If it happens with only the eGPU enabled but not with the other I might have an idea...

**Comment by GregBollella** [comment]
Final render
I have only tested with both enabled. I will try two more tests each with only one gpu enabled.

**Comment by GregBollella** [comment]
With only the 20 enabled: no crash for 15 minutes. Did not see utilization of the 20 though. Render was proceeding super slowly. Game was ok

With only the 56 enabled: no crash for 15 minutes. DID see utilization of the 56. Render was proceeding faster. Game was unusable. 

With both enabled: crash within 6 minutes. Did see utilization of the 56 but not 20. Game was reasonable. 
G

**Comment by bsavery** [comment]
Thanks.  
Just to be completely honest, we're not going to be able to support your game playing at the same time ;) Completely out of scope for us!  You'll probably run into issues with GPU memory utilization.

With both utilized and no game running is it ok?

**Comment by GregBollella** [comment]
LOL... fair enough... no telling which app might be handling the GPU improperly..

**Comment by GregBollella** [comment]
Some observations:
Yes, with both gpus checked and no game all is good. And render is speedy. 


Possible other issues to open:

- In no case do I see any utilization of the 20. nada. zippo. With one or the other or both or both + cpu.

**Comment by GregBollella** [comment]
In all cases *except* *only* two gpus checked does the time on the 'render timestamp' match real-world clock time. With either one checked or all three checked the time in the timestamp behaves oddly. Sometimes faster than wallclock sometimes slower... odd

**Comment by DavidSpeicher** [comment]
Hi, Can you send an image of the GPU usage when both GPUs are enabled?

**Comment by GregBollella** [comment]
Responded in email but not sure you got it. So uploading it here. 
Cheers, 
Greg

![GPU UtilizationWith20And56Enabled](https://user-images.githubusercontent.com/7319340/82593690-bd620880-9b57-11ea-80b3-656a08402dcd.png)

**Comment by bsavery** [comment]
@DavidSpeicher is this still an issue?

**Comment by DavidSpeicher** [comment]
both issues is not reproduced on current release branch. 3.2.1 2.25
