### ISSUE TITLE
Maya 2023 Viewport Issue

### ISSUE THREAD

**Issue by doombotKV** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#353]
I am experiencing that whenever I change a viewport setting the screen always reverts back to whatever it looked like the first time I switch to the ProRender. I can't see wireframes for more than a second before it reverts back. Also getting black screen for AO.

**Comment by DavidSpeicher** [comment]
Hi, @doombotKV 

I can confirm this issue about render reverting back. this is happening only with Render mode changes from what i see. 
About the AO Aov this is a known issue. ill inform the Developers.  thanks

**Comment by DavidSpeicher** [comment]
will be fixed on next update 

As far as AO render mode, this is something we no longer support currently. it was a old Tahoe feature.
there might be plans to bring it back in future but i have no ETA on this currently
