### ISSUE TITLE
Cannot activate ProRenderer Plugin in Maya

### ISSUE THREAD

**Issue by michagrandel** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#355]
Hi there, 

I'm trying to install and use ProRenderer.
I used the Install wizard of Release 3.4, my machine runs Maya 2023 on Windows 11.
I'm following the offical installation instruction from https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/maya/installation.html

The installation went without any errors, but Maya starts with the Plugin deactivated.
if I try to activate the Plugin in Maya's plugin manager, I get this:

> // Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/Program Files/AMD/RadeonProRenderPlugins/Maya/plug-ins/2023/RadeonProRender.mll
> // Die angegebene Prozedur wurde nicht gefunden.
> // Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Die angegebene Prozedur wurde nicht gefunden.
> // (RadeonProRender)

The error message says "line 316: The procedure hasn't been found".

Is there anything I do wrong?
Best, Micha

**Comment by DavidSpeicher** [comment]
hello, 

what language version of Maya are you using? 

if i had to suspect something it would be due to this, we currently only test English version.

**Comment by DavidSpeicher** [comment]
Also please make sure that you dont have any other ProRender installed, such as Maya usd , or blender. 

having other plugins with different SDK can cause this error.
