### ISSUE TITLE
VDB Volume rendering is CPU only. Wrong in the document...

### ISSUE THREAD

**Issue by QuintonQu** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#379]
I can only render the volume with CPU mode toggled, however it says "OpenVDB volumes can be rendered on GPU only, CPU rendering is not supported." on the website. I don't know if this is a typo or something else, but it really borders me. The page is here: https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/maya/openvdb_volumes.html. Hope someone could see this.

**Comment by DavidSpeicher** [comment]
hello,

documment is correct. CPU mode is not supported with VDBs

**Comment by DavidSpeicher** [comment]
hello, 

thanks for letting us know. i will pass this on to the correct person in charge of docs
