### ISSUE TITLE
UDIM do not work

### ISSUE THREAD

**Issue by rhutchins88** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#94]
The version Radeon ProRender for Maya 2.9.42 posted states UDIM support however it does not work. There is no UDIM selection within the ProRender Texture node and when using standard Maya file node, when switching to UDIM the texture stops rendering.

**Comment by bsavery** [comment]
Please attach a scene using the maya file node and I'll have an engineer take a look.

**Comment by DavidSpeicher** [comment]
Hi, 
Currently you need to use RPR 2.0 Northstar engine for UDIMs to work. this feature will not work on RPR 1.0 
Also use Maya file node for this, it is not yet supported with RPR texture node.
